// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: servers.sql

package schema

import (
	"context"

	"github.com/google/uuid"
)

const createServerConfig = `-- name: CreateServerConfig :one
INSERT INTO server_configs (type, config) 
VALUES ($1, $2)
RETURNING id, type, config, created_at, updated_at
`

type CreateServerConfigParams struct {
	Type   string
	Config []byte
}

func (q *Queries) CreateServerConfig(ctx context.Context, arg CreateServerConfigParams) (ServerConfig, error) {
	row := q.db.QueryRow(ctx, createServerConfig, arg.Type, arg.Config)
	var i ServerConfig
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServerConfig = `-- name: GetServerConfig :one
SELECT id, type, config, created_at, updated_at FROM server_configs
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetServerConfig(ctx context.Context, id uuid.UUID) (ServerConfig, error) {
	row := q.db.QueryRow(ctx, getServerConfig, id)
	var i ServerConfig
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServerConfigs = `-- name: GetServerConfigs :many
SELECT id, type, config, created_at, updated_at FROM server_configs
ORDER BY created_at DESC
`

func (q *Queries) GetServerConfigs(ctx context.Context) ([]ServerConfig, error) {
	rows, err := q.db.Query(ctx, getServerConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServerConfig
	for rows.Next() {
		var i ServerConfig
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServerConfig = `-- name: UpdateServerConfig :one
UPDATE server_configs SET 
  config = $2, 
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1 
RETURNING id, type, config, created_at, updated_at
`

type UpdateServerConfigParams struct {
	ID     uuid.UUID
	Config []byte
}

func (q *Queries) UpdateServerConfig(ctx context.Context, arg UpdateServerConfigParams) (ServerConfig, error) {
	row := q.db.QueryRow(ctx, updateServerConfig, arg.ID, arg.Config)
	var i ServerConfig
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
